//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.subCategories = new HashSet<Category>();
            this.Products = new HashSet<Product>();
        }
    
        public int categoriesID { get; set; }
        public string name { get; set; }
        public Nullable<int> parentID { get; set; }
    
        public virtual ICollection<Category> subCategories { get; set; }
        public virtual Category parentCategory { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
