//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderLines = new HashSet<OrderLine>();
        }
    
        public int OrdersID { get; set; }
        public Nullable<int> shippingAddressID { get; set; }
        public Nullable<int> billingAddressID { get; set; }
        public Nullable<int> paymentID { get; set; }
        public Nullable<int> shippingID { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<decimal> totalPrice { get; set; }
        public Nullable<decimal> salesTax { get; set; }
        public Nullable<decimal> subTotal { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<System.DateTime> dateCompleted { get; set; }
        public Nullable<System.DateTime> dateShipped { get; set; }
        public Nullable<int> shippingPrice { get; set; }
        public string status { get; set; }
    
        public virtual Address shippingAddress { get; set; }
        public virtual Address billingAddress { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Shipment Shipment { get; set; }
        public virtual ICollection<OrderLine> OrderLines { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
