//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public int orderLinesID { get; set; }
        public int quanity { get; set; }
        public string productName { get; set; }
        public int productID { get; set; }
        public decimal unitPrice { get; set; }
        public decimal subTotal { get; set; }
        public int orderID { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
