//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Images = new HashSet<Image>();
        }
    
        public int productID { get; set; }
        public int price { get; set; }
        public string name { get; set; }
        public int quantity { get; set; }
        public string description { get; set; }
        public int categoriesID { get; set; }
        public int suppliersID { get; set; }
    
        public virtual ICollection<Image> Images { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Category Category { get; set; }
    }
}
