//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int suppliersID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string imageURl { get; set; }
        public string address { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
